{
 "title": "Orynx Chain Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(side_car_api_http_status_code,job)"
    }
   },
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values({job=\"$job\"},chain_id)"
    }
   },
   {
    "name": "ticker",
    "label": "Reported Ticker",
    "query": {
     "query": "label_values(app_prices{job=\"$job\"},ticker)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price{job=\"$job\"},id)"
    }
   },
   {
    "name": "provider",
    "label": "Data Provider",
    "query": {
     "query": "label_values(side_car_health_check_provider_updates_total{job=~\"$job\"},provider)"
    }
   },
   {
    "name": "valscon",
    "label": "Validator Address",
    "query": {
     "query": "label_values(app_report_status_per_validator{job=\"$job\"},validator)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Network Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Total # of Produced Blocks in Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of Extra Rounds in Range",
   "type": "stat",
   "description": "The total number of extra rounds of consensus over the time range.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_rounds{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_latest_block_height{job=~\"${job}\", chain_id=~\"${chain_id}\"}[$__range])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / (rate(cometbft_consensus_latest_block_height{job=~\"${job}\", chain_id=~\"${chain_id}\"}[$__range]))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Transactions / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_num_txs{job=~\"${job}\", chain_id=~\"${chain_id}\"}[$__range])"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1h]))   ",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=~\"${job}\", chain_id=~\"${chain_id}\"}[24h]))",
     "legendFormat": "1 Day"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=~\"${job}\", chain_id=~\"${chain_id}\"}[7d]))   ",
     "legendFormat": "7 Day"
    }
   ]
  },
  {
   "title": "Total # of Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "Voting Power"
    },
    {
     "expr": "avg(cometbft_consensus_validator_power{job=~\"${job}\", chain_id=~\"${chain_id}\"}) / avg(cometbft_consensus_validators_power{job=~\"${job}\", chain_id=~\"${chain_id}\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens on Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "ABCI Method Status Reports in Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(app_abci_requests{job=~\"${job}\", chain_id=~\"${chain_id}\"}) by (status, abci_method)",
     "legendFormat": "{{abci_method}} {{status}}"
    }
   ]
  },
  { "title": "Market Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "${ticker} Market Price On Chain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "repeat": "ticker",
   "targets": [
    {
     "expr": "app_prices{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\"} ",
     "legendFormat": "{{ticker}} - On Chain"
    }
   ]
  },
  {
   "title": "${ticker} Market Prices Per Validator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "repeat": "ticker",
   "targets": [
    {
     "expr": "app_reports_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", validator=~\"${valscon}\"}  ",
     "legendFormat": "{{ticker}} - {{validator}}"
    },
    {
     "expr": "app_prices{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\"} ",
     "legendFormat": "{{ticker}} - On Chain"
    }
   ]
  },
  {
   "title": "% of Validators with Price Update for ${ticker}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "repeat": "ticker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", status=\"with_price\", validator=~\"${valscon}\"}) \n/ \nsum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", validator=~\"${valscon}\"}))\n* \n100",
     "legendFormat": "with price"
    },
    {
     "expr": "(sum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", status=\"absent\", validator=~\"${valscon}\"}) \n/ \nsum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", validator=~\"${valscon}\"}))\n* \n100",
     "legendFormat": "absent"
    },
    {
     "expr": "(sum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", status=\"missing_price\", validator=~\"${valscon}\"}) \n/ \nsum(app_report_status_per_validator{job=~\"${job}\", chain_id=~\"${chain_id}\", ticker=~\"${ticker}\", validator=~\"${valscon}\"}))\n* \n100",
     "legendFormat": "missing price"
    }
   ]
  },
  { "title": "Chain Latency & P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 594 } },
  {
   "title": "ABCI Method Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 595 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m]) / rate(cometbft_abci_connection_method_timing_seconds_count{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ABCI Method Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 595 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_abci_method_latency_sum{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m]) / rate(app_abci_method_latency_count{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m])",
     "legendFormat": "{{abci_method}}"
    }
   ]
  },
  {
   "title": "Average Size of Oracle Message Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 603 },
   "targets": [
    {
     "expr": "rate(app_message_size_sum{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m])\n/\nrate(app_message_size_count{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 603 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "Block size"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 611 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m]) / rate(cometbft_consensus_block_interval_seconds_count{job=~\"${job}\", chain_id=~\"${chain_id}\"}[1m])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 611 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "Mempool"
    }
   ]
  },
  {
   "title": "Failed Transactions / sec (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 619 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_failed_txs{job=~\"${job}\", chain_id=~\"${chain_id}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txs/block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 619 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 627 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=~\"${job}\", chain_id=~\"${chain_id}\"}",
     "legendFormat": "Peers - {{instance}}"
    }
   ]
  }
 ]
}