{
 "title": "Orynx SideCar Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(side_car_provider_price,job)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price{job=~\"$job\"},id)"
    }
   },
   {
    "name": "provider",
    "label": "Price Provider",
    "query": {
     "query": "label_values(side_car_health_check_provider_updates_total{job=~\"$job\"},provider)"
    }
   },
   {
    "name": "market_map_provider",
    "label": "Market Map Provider",
    "query": {
     "query": "label_values(side_car_provider_status_responses_per_id,provider)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Side Car Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "side_car_orynx_build_info{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of Aggregated Feeds + Provider Feeds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job) (side_car_aggregated_price{job=~\"${job}\"})",
     "legendFormat": "Aggregated {{job}}"
    },
    {
     "expr": "count by (job) (side_car_provider_price{job=~\"${job}\"})",
     "legendFormat": "Provider {{job}}"
    }
   ]
  },
  {
   "title": "Number of Prices Fetched / Sec in Range",
   "type": "stat",
   "description": "Number of successful price updates that were fetched by WebSocket and API providers per second.",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(side_car_provider_status_responses{job=~\"${job}\", status=\"success\", provider=~\"${provider}\"}[$__range]))",
     "legendFormat": "{{job}} prices / sec"
    },
    {
     "expr": "sum by (job) (increase(side_car_provider_status_responses{job=~\"${job}\", status=\"success\", provider=~\"${provider}\"}[$__range]))",
     "legendFormat": "{{job}} total prices"
    }
   ]
  },
  {
   "title": "Side Car Price Aggregation Tick Interval",
   "type": "stat",
   "description": "The number times per second that the side-car attempts to calculate a final price from all of the providers in range.",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(side_car_health_check_system_updates_total{job=~\"${job}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Attempted Price Calculations in Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(increase(side_car_health_check_system_updates_total{job=~\"${job}\"}[$__range]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Price Update % in Range Graphed",
   "type": "timeseries",
   "description": "This table is tracking the number of attempted price aggregations to the actual number of aggregations. So effectively this ratio tells us how often we were able to get a final aggregated price.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (id, job) \n(rate(side_car_health_check_ticker_updates_total{job=~\"${job}\"}[$__range]))\n/\nscalar(rate(side_car_health_check_system_updates_total{job=~\"${job}\"}[$__range])) * 100",
     "legendFormat": "{{id}} {{job}}"
    }
   ]
  },
  {
   "title": "Successful Price Update % in Range",
   "type": "stat",
   "description": "Percentage of successful price updates relative to the expected number of updates in range.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) \n(rate(side_car_health_check_ticker_updates_total{job=~\"${job}\"}[$__range]))\n/\nscalar(rate(side_car_health_check_system_updates_total{job=~\"${job}\"}[$__range]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Number of Successful Price Updates in Side Car in Range",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(side_car_health_check_ticker_updates_total{job=\"${job}\"}[$__range])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Sidecar logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |= `` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"${job}\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Side Car Aggregated Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Price Change in Time Range for ${id}",
   "type": "stat",
   "gridPos": { "h": 15, "w": 1, "x": 0, "y": 64 },
   "repeat": "id",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg_over_time(side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"}[5m]) - side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 5m) / side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 5m",
     "legendFormat": "5m"
    },
    {
     "expr": "100 * (avg_over_time(side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"}[1h]) - side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 1h) / side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 1h",
     "legendFormat": "1h"
    },
    {
     "expr": "100 * (avg_over_time(side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"}[6h]) - side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 6h) / side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 6h",
     "legendFormat": "6h"
    },
    {
     "expr": "100 * (avg_over_time(side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"}[24h]) - side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 24h) / side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"} offset 24h",
     "legendFormat": "24h"
    }
   ]
  },
  {
   "title": "${id} Market",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 1, "y": 64 },
   "repeat": "id",
   "targets": [
    {
     "expr": "side_car_aggregated_price{job=~\"${job}\", id=~\"${id}\"}",
     "legendFormat": "index {{job}}"
    },
    {
     "expr": "side_car_provider_price{job=~\"${job}\", id=~\"${id}\", provider=~\"${provider}\"}",
     "legendFormat": "{{provider}}  {{job}}"
    }
   ]
  },
  {
   "title": "Number of Available Provider Prices for ${id}",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 64 },
   "repeat": "id",
   "targets": [
    {
     "expr": "side_car_health_check_market_providers{job=~\"${job}\", id=~\"${id}\"}",
     "legendFormat": "{{id}} {{job}}"
    }
   ]
  },
  { "title": "Side Car Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1129 } },
  {
   "title": "Data Provider HTTP 2XX % in Range",
   "type": "stat",
   "description": "Percentage of requests from sidecar to data provider that were successful in the time range of the dashboard",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1130 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\",status_code=\"2XX\"}[$__range]))) / (sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\"}[$__range])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Message Handling % in Range",
   "type": "stat",
   "description": "Percentage of web socket messages from sidecar to data provider that were successful handled in the time range of the dashboard.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1130 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_data_handler_status{job=\"${job}\",status=~\"create_message_success|handle_message_success|heartbeat_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_data_handler_status{job=\"${job}\"}[$__range])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider HTTP Status Code / sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1134 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(side_car_api_http_status_code{job=\"${job}\"}[$__range])) by (status_code,provider)",
     "legendFormat": "{{provider}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "# of Successful Reads / Sec by Provider in Range",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1134 },
   "targets": [
    {
     "expr": "rate(side_car_web_socket_connection_status{job=~\"${job}\", provider=~\"${provider}\", status=~\"read_success\"}[5m])",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Median Round Trip Latency by API Provider",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1146 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(side_car_api_response_latency_bucket{job=~\"${job}\"}[$__range])) by (le, provider))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Median Latency between Message Receives by WebSocket Provider",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1146 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(side_car_web_socket_response_time_bucket{job=~\"${job}\", provider=~\"${provider}\"}[$__range])) by (le, provider))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Connection Reads % in Range",
   "type": "stat",
   "description": "Percentage of reads that were successfully made on the underlying connection by the data provider in the range. Note that a lower percentage doesn't necessarily imply that the connection is bad - it could just mean that it has received fewer updates.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1154 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"read_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"read_success|read_err\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Provider Successful WebSocket Connection Writes % in Range",
   "type": "stat",
   "description": "The percentage of successful writes made by web socket data providers in the range.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1158 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"write_success|dial_success\"}[$__range]))) / (sum by (provider) (increase(side_car_web_socket_connection_status{job=\"${job}\",status=~\"write_success|write_err|dial_success|dial_error\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of New WebSocket Connections in Range",
   "type": "stat",
   "description": "This metric tracks the total number of times a successful connection was created to the relevant providers.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1162 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "side_car_web_socket_connection_status{job=~\"${job}\", provider=~\"${provider}\", status=\"healthy\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Detailed Side Car ${provider} Market Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1166 },
   "repeat": "provider",
   "collapsed": true,
   "panels": [
    {
     "title": "# of Price Feeds for ${provider}",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 110 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum (increase(side_car_health_check_provider_updates_total{job=~\"$job\", id=~\"${id}\", provider=~\"${provider}\", success=~\"false|true\"}[$__range])) by (id))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# of Price Feeds with > 95% Success Rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 110 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count((sum by (provider, id) (increase(side_car_health_check_provider_updates_total{job=\"${job}\", success=\"true\", provider=~\"${provider}\"}[$__range])) / sum by (provider, id) (increase(side_car_health_check_provider_updates_total{job=\"${job}\", provider=~\"${provider}\", success=~\"true|false\"}[$__range]))) > 0.95)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Provider ${provider} Fetch Success % in Range",
     "type": "stat",
     "description": "Percentage of how often we were able to successfully retrieve a price from a provider per market when expected.",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - (\n    sum by (provider, id) \n    (increase(side_car_health_check_provider_updates_total{job=\"${job}\", success=\"false\", provider=~\"${provider}\"}[$__range])) \n    / \n    sum by (provider, id) \n    (increase(side_car_health_check_provider_updates_total{job=\"${job}\", provider=~\"${provider}\", success=~\"true|false\"}[$__range]))\n)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Price Feed Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "(1 - (\n    sum by (provider, id) \n    (increase(side_car_health_check_provider_updates_total{job=\"${job}\", success=\"false\", provider=~\"${provider}\"}[$__range])) \n    / \n    sum by (provider, id) \n    (increase(side_car_health_check_provider_updates_total{job=\"${job}\", provider=~\"${provider}\", success=~\"true|false\"}[$__range]))\n)) * 100",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  { "title": "Solana Node Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1188 } },
  {
   "title": "Solana Node Provider Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1189 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "          sum(rate(\n              side_car_api_rpc_status_code{job=~\"${job}\", provider=\"raydium_api\", status_code=\"ok\"}[5m]\n          )) by (provider, endpoint) /\n          sum(rate(\n              side_car_api_rpc_status_code{job=~\"${job}\", provider=\"raydium_api\"}[5m]\n          )) by (provider, endpoint) * 100",
     "legendFormat": "{{provider}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Solana Node Provider Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1189 },
   "targets": [
    {
     "expr": "sum(rate(side_car_api_response_latency_sum{provider=\"raydium_api\", job=~\"${job}\"}[5m])) by (le, endpoint) / sum(rate(side_car_api_response_latency_count{provider=\"raydium_api\", job=~\"${job}\"}[5m])) by (le, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Solana RPC Node Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1197 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(side_car_api_response_latency_bucket{provider=\"raydium_api\", job=~\"${job}\"}[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}